# uvg_core/schema_v2.py
"""
UVG MAX JSON Schema v2.1 - Comprehensive Video Production Schema

This schema controls the ENTIRE pipeline:
- Video metadata and aesthetic calibration
- Music profile and sound design
- Scene-level clips, voiceover, VFX, SFX, captions
- Thumbnail generation
- License metadata and attribution tracking

Word timestamps are AUTO-GENERATED by Whisper - never manually entered!
License metadata is AUTO-POPULATED when clips are downloaded!
"""

from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional
from enum import Enum


# =============================================================================
# ENUMS FOR VALIDATION
# =============================================================================

class NarrativeStyle(str, Enum):
    CINEMATIC = "cinematic"
    MOTIVATIONAL = "motivational"
    DOCUMENTARY = "documentary"
    EMOTIONAL = "emotional"
    STORYTELLING = "storytelling"
    TIKTOK = "tiktok"


class Emotion(str, Enum):
    MOTIVATIONAL = "motivational"
    SAD = "sad"
    PEACEFUL = "peaceful"
    TENSE = "tense"
    HAPPY = "happy"
    DRAMATIC = "dramatic"
    EXCITING = "exciting"
    CALM = "calm"
    MYSTERIOUS = "mysterious"
    NEUTRAL = "neutral"


class MusicGenre(str, Enum):
    AMBIENT = "ambient"
    CINEMATIC = "cinematic"
    EPIC = "epic"
    SOFT_PIANO = "soft_piano"
    DARK = "dark"
    ELECTRONIC = "electronic"
    ORCHESTRAL = "orchestral"


class SyncMode(str, Enum):
    DUCKING = "ducking"
    EMOTIONAL = "emotional"
    BEAT_REACTIVE = "beat_reactive"


class CameraMotion(str, Enum):
    SLOW_PAN_LEFT = "slow_pan_left"
    SLOW_PAN_RIGHT = "slow_pan_right"
    TILT_UP = "tilt_up"
    TILT_DOWN = "tilt_down"
    STATIC = "static"
    ZOOM_IN = "zoom_in"
    ZOOM_OUT = "zoom_out"
    PARALLAX = "parallax"
    KEN_BURNS = "ken_burns"


class ShotType(str, Enum):
    WIDE = "wide"
    MEDIUM = "medium"
    CLOSEUP = "closeup"
    AERIAL = "aerial"
    MACRO = "macro"


class Transition(str, Enum):
    FADE = "fade"
    SLIDE_LEFT = "slide_left"
    SLIDE_RIGHT = "slide_right"
    WIPE = "wipe"
    FILM_BURN = "film_burn"
    CROSS_ZOOM = "cross_zoom"
    GLITCH = "glitch"


class ColorGrade(str, Enum):
    CINEMATIC = "cinematic"
    WARM = "warm"
    COLD = "cold"
    DRAMATIC = "dramatic"
    VINTAGE = "vintage"
    DOCUMENTARY = "documentary"
    PASTEL = "pastel"


class VoiceStyle(str, Enum):
    DOCUMENTARY = "documentary"
    MOTIVATIONAL = "motivational"
    CINEMATIC = "cinematic"
    TIKTOK_FAST = "tiktok_fast"
    CALM_NARRATIVE = "calm_narrative"
    ENERGETIC_HYPE = "energetic_hype"
    NEUTRAL = "neutral"


class Orientation(str, Enum):
    PORTRAIT = "portrait"      # 9:16 (1080x1920)
    LANDSCAPE = "landscape"    # 16:9 (1920x1080)
    SQUARE = "square"          # 1:1 (1080x1080)


# =============================================================================
# COMPLETE JSON SCHEMA v2.1
# =============================================================================

SCHEMA_TEMPLATE = {
    "version": "2.1",
    
    # =========================================================================
    # VIDEO METADATA
    # =========================================================================
    "video_meta": {
        "title": "",
        "description": "",
        "narrative_style": "cinematic",  # cinematic | motivational | documentary | tiktok
        "target_duration_seconds": 60,
        "orientation": "portrait",  # portrait | landscape | square
        "resolution": {"width": 1080, "height": 1920},  # Explicit resolution
        "global_emotion": "motivational",
        "language": "en-US",
        "include_captions": True,
        "thumbnail_enabled": True,  # Generate thumbnail at end
        
        # Reproducibility
        "deterministic_mode": False,
        "random_seed": None,
    },
    
    # =========================================================================
    # MUSIC PROFILE
    # =========================================================================
    "music_profile": {
        "source": {
            "path": None,           # Local file path OR
            "search_query": None,   # API search query
        },
        "genre": "cinematic",       # ambient | cinematic | epic | soft_piano | dark
        "bpm": 120,                 # Beats per minute (for beat_reactive sync)
        "intensity_curve": "wave",  # rise | fall | wave | constant
        "sync_mode": "ducking",     # ducking | emotional | beat_reactive
        "volume_percent": 15,       # Background music volume (0-100)
        
        # Global sound design elements
        "sound_design": ["whoosh", "hit", "riser"],
    },
    
    # =========================================================================
    # THUMBNAIL CONCEPT
    # =========================================================================
    "thumbnail_concept": {
        "headline": "",
        "pose_or_subject": "",
        "emotion": "",
        "color_style": "warm",  # warm | cold | high_contrast | neon | pastel
        "background_type": "blurred_frame",  # gradient | solid | blurred_frame
        "effects": ["outline", "glow"],
    },
    
    # =========================================================================
    # AESTHETIC CALIBRATION
    # =========================================================================
    "aesthetic_calibration": {
        "primary_color_grade": "cinematic",
        "overall_lut": "cinematic_lut.cube",
        "pacing_profile": "dynamic",  # slow | medium | fast | dynamic
        "shot_variation_goal": "high",  # high | medium | low
    },
    
    # =========================================================================
    # VOICEOVER SETTINGS (Global defaults)
    # =========================================================================
    "voiceover": {
        "voice_style": "documentary",  # Fish-Speech S1 preset
        "speed": 1.0,
        "emotion": "(calm)",  # Fish-Speech emotion marker
        "reference_audio": None,  # For voice cloning
    },
    
    # =========================================================================
    # CAPTION SETTINGS (Global defaults)
    # =========================================================================
    "caption_defaults": {
        "font": "Inter Bold",
        "size": 42,
        "color": "#FFFFFF",
        "outline_color": "#000000",
        "position": "bottom",  # bottom | center | top
        "animation": "word_reveal",  # slide_up | pop | bounce | fade | word_reveal
        "max_words_per_line": 4,
    },
    
    # =========================================================================
    # SCENES (Main content)
    # =========================================================================
    "scenes": [
        {
            "scene_id": 1,
            "text": "",  # Narration text
            "duration_seconds": 5,
            
            # Emotion & Style
            "emotion": "neutral",  # Drives VFX/SFX/music
            "voice_style": None,  # Override global voiceover
            
            # Clip/Visual Settings
            "shot_type": "medium",
            "camera_motion": "zoom_in",
            "speed_ramp": {"in": 1.0, "out": 1.0},  # Speed multipliers
            "frame_composition": "rule_of_thirds",
            "visual_descriptor": "",  # Detailed visual description
            "search_keywords": "",  # Stock footage search
            
            # Color & Grade
            "color_grade": None,  # Override global
            "lut": None,  # Override global LUT
            "lighting": "natural",  # natural | warm | cold | dramatic
            
            # Transition to next scene
            "transition": "fade",
            
            # VFX (Per-scene effects)
            "vfx": {
                "effects": ["subtle_glow", "film_grain"],  # List of effects
                "bloom": None,  # Override from emotion
                "contrast": None,
                "saturation": None,
                "vignette": None,
            },
            
            # SFX / Sound Design (Per-scene)
            "sound_design": {
                "use_hit": False,
                "use_whoosh": False,
                "use_riser": False,
                "custom_sfx": None,  # Path to custom SFX
            },
            
            # Caption (Per-scene override)
            "caption_style": None,  # Override global
            
            # Word timestamps (AUTO-GENERATED by Whisper - DO NOT FILL)
            "word_timestamps": [],  # Will be populated automatically
            
            # Selected clip info (AUTO-POPULATED after clip selection)
            "selected_clip": {
                "provider": None,      # pexels | pixabay | unsplash
                "asset_id": None,      # Provider's ID
                "license_type": None,  # License key
                "attribution": None,   # Attribution text
                "original_url": None,  # Link to source
                "downloaded_path": None,  # Local path
            },
        }
    ],
}


# =============================================================================
# SCHEMA CONVERTER (Old format → New format)
# =============================================================================

def convert_legacy_schema(old_data: Dict) -> Dict:
    """
    Convert legacy JSON schema to v2.0 format.
    
    Supports:
    - Old flat scene format
    - Missing video_meta block
    - Missing music_profile block
    """
    new_data = {
        "version": "2.0",
        "video_meta": {},
        "music_profile": {},
        "scenes": [],
    }
    
    # Convert video_meta
    if "video_meta" in old_data:
        new_data["video_meta"] = old_data["video_meta"]
    else:
        new_data["video_meta"] = {
            "title": old_data.get("title", "Untitled"),
            "narrative_style": old_data.get("style", "cinematic"),
            "target_duration_seconds": old_data.get("total_duration", 60),
            "global_emotion": old_data.get("emotion", "neutral"),
            "language": old_data.get("language", "en-US"),
            "include_captions": True,
            "deterministic_mode": old_data.get("deterministic_mode", False),
            "random_seed": old_data.get("random_seed"),
        }
    
    # Convert music_profile
    if "music_profile" in old_data:
        new_data["music_profile"] = old_data["music_profile"]
    elif "music" in old_data:
        music = old_data["music"]
        new_data["music_profile"] = {
            "source": {
                "path": music.get("path"),
                "search_query": music.get("search_query"),
            },
            "sync_mode": music.get("sync_mode", "ducking"),
        }
    
    # Convert scenes
    for i, scene in enumerate(old_data.get("scenes", [])):
        new_scene = {
            "scene_id": scene.get("scene_id", scene.get("index", i + 1)),
            "text": scene.get("text", scene.get("narration", "")),
            "duration_seconds": scene.get("duration_seconds", scene.get("duration", 4)),
            "emotion": scene.get("emotion", scene.get("scene_emotion", "neutral")),
            "voice_style": scene.get("voice_style"),
            "camera_motion": scene.get("camera_motion", "zoom_in"),
            "visual_descriptor": scene.get("visual_descriptor", scene.get("visual_query", "")),
            "search_keywords": scene.get("search_keywords", scene.get("visual_query", "")),
            "transition": scene.get("transition", "fade"),
        }
        
        # Convert speed_ramp
        if "speed_ramp" in scene:
            if isinstance(scene["speed_ramp"], dict):
                new_scene["speed_ramp"] = scene["speed_ramp"]
            else:
                new_scene["speed_ramp"] = {"in": 1.0, "out": float(scene["speed_ramp"].replace("x", ""))}
        
        # Convert VFX
        if "vfx" in scene:
            if isinstance(scene["vfx"], list):
                new_scene["vfx"] = {"effects": scene["vfx"]}
            else:
                new_scene["vfx"] = scene["vfx"]
        
        # Convert sound_design
        if "sound_design" in scene:
            new_scene["sound_design"] = scene["sound_design"]
        
        new_data["scenes"].append(new_scene)
    
    return new_data


def get_schema_template() -> Dict:
    """Get a copy of the schema template."""
    import copy
    return copy.deepcopy(SCHEMA_TEMPLATE)


def validate_schema(data: Dict) -> List[str]:
    """
    Validate JSON against schema v2.0.
    
    Returns list of error messages (empty if valid).
    """
    errors = []
    
    # Check version (accept 2.0 or 2.1)
    version = data.get("version", "")
    if version not in ("2.0", "2.1"):
        errors.append(f"Missing or invalid 'version' (expected '2.0' or '2.1', got '{version}')")
    
    # Check video_meta
    if "video_meta" not in data:
        errors.append("Missing 'video_meta' block")
    
    # Check scenes
    if "scenes" not in data or len(data.get("scenes", [])) == 0:
        errors.append("Missing or empty 'scenes' array")
    
    # Validate each scene
    for i, scene in enumerate(data.get("scenes", [])):
        if not scene.get("text"):
            errors.append(f"Scene {i+1}: Missing 'text' field")
    
    return errors
